search/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('search_fitur.urls')),
    path('admin/', admin.site.urls),
]

search_fitur/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'search_fitur'
urlpatterns = [
    path('', views.index, name='index'),
    path('result/', views.searchposts, name='cari'),
    # path('category/<str:kategori>/', views.kategori, name='awal'),
    path('category/', views.kategori, name='awal'),
    path('<int:blog_id>/', views.coba, name='halo'),
    path('coba/', views.coba, name='wow'),
    path('category/<str:kategori>/', views.searchposts2, name="kategori")
   
]

search_fitur/models.py
from django.db import models
from datetime import datetime
from ckeditor.fields import RichTextField

# Create your models here.


class User(models.Model):
    username=models.CharField(max_length=200)
    nama_lengkap=models.CharField(max_length=200)
    jabatan=models.CharField(max_length=200)
    sosmed=models.CharField(max_length=200)
    email=models.CharField(max_length=200)
    password=models.CharField(max_length=200)
    profile=models.CharField(max_length=200)

    def __str__(self):
        return self.nama_lengkap

class Post(models.Model):
    title=models.CharField(max_length=200)
    date= models.DateTimeField(default=datetime.now)
    author=models.ForeignKey(User, on_delete=models.CASCADE)
    konten=models.CharField(max_length=3000)
    gambar=models.CharField(max_length=200)
    kategori=models.CharField(max_length=200,default="Dessert")

    def __str__(self):
        return self.title

class Komen(models.Model):
    user_id=models.ForeignKey(User, on_delete=models.CASCADE)
    post_id=models.ForeignKey(Post, on_delete=models.CASCADE)
    date= models.DateTimeField(default=datetime.now)
    komen=models.CharField(max_length=200)
   

    def __str__(self):
        return str(self.post_id)

search_fitur/views.py
from django.shortcuts import render
from .models import Post, User,Komen
from django.db.models import Q


# Create your views here.
def index(request):
    blog=Post.objects.all()
    komen=Komen.objects.all()
    ctx={"blogs": blog, 'komen':komen}
    return render(request, 'search_fitur/index.html', ctx)

def coba(request, blog_id):
    blog=Post.objects.filter(pk=blog_id)
    komen=Komen.objects.filter(post_id=blog_id)
    ctx={'blog':blog, 'komen':komen}
    return render(request, 'search_fitur/detail.html', ctx )

def kategori(request):
    blog=Post.objects.all().distinct()
    return render(request, "search_fitur/category1.html", {"blogs":blog})

def display_kategori(request):
    return render(request, 'search_fitur/category1.html', {})

def searchposts(request):
    if request.method == 'GET':
        query= request.GET.get('q')

        submitbutton= request.GET.get('submit')

        if query is not None:
            lookups= Q(title__icontains=query) | Q(konten__icontains=query)
            new= Q(nama_lengkap__icontains=query)

            results= Post.objects.filter(lookups).distinct()
            user_result=User.objects.filter(new).distinct()

            context={'results': results,
                     'user': user_result}

            return render(request, 'search_fitur/search.html', context)

        else:
            return render(request, 'search_fitur/index.html')

    else:
        return render(request, 'search_fitur/index.html')


def searchposts2(request, kategori):

    query= kategori

    submitbutton= request.GET.get('submit')

    if query is not None:
        lookups= Q(kategori__icontains=query) 

        results= Post.objects.filter(lookups).distinct()
            

        context={'results': results}

        return render(request, 'search_fitur/category2.html', context)

    else:
        return render(request, 'search_fitur/index.html')

search_fitur/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Toko Online</title>
    {%load static%}
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <link rel="stylesheet" href="{%static 'js/bootstrap.min.js'%}">
    <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
</head>

<!------------------------------------------- header ------------------------------------------->
<header>
    <div class="wrap-container--header">
        <div class="container">
            <div class="row align-items-center blok-header">
                <div class="col-md-6 align-items-center company-name">
                    Toko Online
                </div>
                <div class="col-md-6">
                    <div class="header-nav">
                        <ul class="header-nav__list list-unstyled">  
                            <li> 
                                <a href="{%url 'onlineshop:index'%}">Home</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!------------------------------------------- EOF header ------------------------------------------->

<body>
    <div class="wrap-base--content">
        {% block content %}
        {% endblock %}        
    </div>
</body>

</html>

search_fitur/templates/base/base.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <title> Search Fitur</title>
    </head>
    <body>
        {% block content%}
        {% endblock%}

    </body>
</html>

search_fitur/templates/search_fitur/category1.html
{% extends 'base/base.html'%}
{% block content %}
<div class="wrap-cat1">
    <div class="container">
        <ul>
            {%for blog in blogs%}
                <li><a href="{{blog.kategori}}" name="click">{{blog.kategori}}</a></li>
            {% endfor %}
        </ul>            
    </div>
</div>
                
{% endblock %}

search_fitur/templates/search_fitur/category2.html
{% extends 'base/base.html'%}
{% block content %}

<div class="wrap-cat2">
    <div class="container">
        {%for i in results%}
          <div>
            <img width="300px" src="{{i.gambar}}"/>"
            <p>{{i.title}}</p>
            <p><strong>{{i.author}}</strong></p>
             <p>{{i.konten}}</p>
          </div>
        {%endfor%}
    </div>
</div>

{% endblock %}

search_fitur/templates/search_fitur/detail.html
<!-- Menampilakan artikel lengkap plus komennya -->

<div class="wrap-detail">
    <div class="container">
        {%for i in blog%}
         <p>{{i.id}}</p>
         <p>{{i.title}}</p>
         <p>{{i.konten}}</p>
          {%for j in komen%}
            <p>{{j.user_id}}</p>
            <p>{{j.komen}}</p>
          {%endfor%}
        {%endfor%}
    </div>
</div>

search_fitur/templates/search_fitur/form.html
{%extends 'base.html'%}
{%block title%}Toko Online{%endblock%}


{%block content%}

{%endblock%}

search_fitur/templates/search_fitur/index.html
{% extends 'base/base.html'%}
{% block content %}
        <br/>
       <!-- ini fitur search -->
       <div class="wrap-search">
         <div class="container">
           <div style="width:900px; height:90px" id="header-search">
             <form action="{% url 'search_fitur:cari' %}" method="GET" value="{{request.GET.q}}">
               <div class="input-group-prepend">  
                 <span class="input-group-text" id="basic-addon1"><img src=""></span>
                 <input  class="form-control" list="title" type="text" name="q" value="{{request.GET.q}}" placeholder="What's cooking?"/>
                 <datalist id="title">
                 {% for i in blogs %}
                   <option value="{{i.title}}">
                 {% endfor %}
                 </datalist>
                </div>
             </form>
           </div>
          </div>
      </div>


        <!-- ini nampilin preview blog di homepage -->
        <div class="wrap-blog">
          <div class="container">
           {% for p in blogs %}
            <img src={{p.gambar}}/>
            <p>{{p.title}}</p>
            <p>{{p.author}}</p>
      
            <a href="{{p.id}}">Details</a>
            </br>
           {%endfor%}
          </div>
        </div>



        <!-- logic search -->
        {% if request.GET.q != '' %}
        {% if results %}
        <h1>Results for <b>{{ request.GET.q }}</b></h1>
        <br/><br/>
        {% for result in results %}
        {{result.title}}
        <br/>
        {{result.konten}}
        <br/>
        {% endfor %}
        {% else %}
        No search results for this query
        {% endif %} 
        {% endif %}
{% endblock %}

search_fitur/templates/search_fitur/search.html
{% extends 'base/base.html'%}
{% block content %}
<!-- menmapilkan hasil pencarian -->
<div class="wrap-searchresult">
    <div class="container">
        {%for i in results%}
        <div>
            <img width="300px" src="{{i.gambar}}"/>"
            <p>{{i.title}}</p>
            <p><strong>{{i.author}}</strong></p>
            <p>{{i.konten}}</p>
        </div>
        {%endfor%}
    </div>
</div>


{% endblock %}